### ISSUE TITLE
[COMPILER] java.util.zip.ZipException: duplicate entry: META-INF/MANIFEST.MF

### ISSUE THREAD

**Issue by MWGuy** [jphp-group/jphp-android#2]
```
---> start compiling...
 -> src: ./build/out
 -> dest: ./libs/compile.jar.temp
 -> dest-res: null

---> compile: ./build/out/index.php
---> compile: ./build/out/app/App.php
java.util.zip.ZipException: duplicate entry: META-INF/MANIFEST.MF
	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)
	at java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:109)
	at org.venity.compiler.Main$1.call(Main.java:275)
	at org.venity.compiler.Main$1.call(Main.java:264)
	at org.venity.compiler.Main.scan(Main.java:400)
	at org.venity.compiler.Main.scan(Main.java:407)
	at org.venity.compiler.Main.compileJar(Main.java:264)
	at org.venity.compiler.Main.main(Main.java:130)

Compiling is SUCCESSFUL, time = 1395ms.
```

**Comment by KakinGT** [comment]
Let me Help You
